# CircuitPython
CIRCUITPY_BLE_NAME="synthio-mono"

# Midi
MIDI_MAX_CHANNEL=15
MIDI_MIN_CHANNEL=0
MIDI_UART=1 #bool
MIDI_UART_TX="GP4"
MIDI_UART_RX="GP5"
MIDI_USB=0 #bool
MIDI_BLE=0 #bool

# Display
DISPLAY_TYPE="1602"
DISPLAY_RS="GP27"
DISPLAY_EN="GP26"
DISPLAY_D4="GP21"
DISPLAY_D5="GP20"
DISPLAY_D6="GP19"
DISPLAY_D7="GP18"
DISPLAY_VO="GP28"
DISPLAY_CONTRAST=25 #/100

# Encoder
ENCODER_A="GP11"
ENCODER_B="GP12"
ENCODER_BTN="GP13"

# Audio
AUDIO_RATE=22050
AUDIO_BUFFER=4096
AUDIO_TYPE="i2s"
AUDIO_CLK="GP6"
AUDIO_WS="GP7"
AUDIO_DATA="GP8"

# Arpeggiator
ARP_MAX_BPM=240
ARP_MIN_BPM=60
ARP_MAX_GATE=100 #/100
ARP_MIN_GATE=10 #/100

# Waveforms
WAVE_SAMPLES=256
WAVE_AMPLITUDE=12000

# Oscillator
OSC_MAX_COARSE_TUNE=300 #/100
OSC_MAX_FINE_TUNE=8 #/100
OSC_MAX_BEND=100 #/100
OSC_MAX_GLIDE=200 #/100
OSC_MIN_GLIDE=1 #/100
OSC_FILTER_MAX_FREQ=20000
OSC_FILTER_MIN_FREQ=120
OSC_FILTER_MAX_RESO=1600 #/100
OSC_FILTER_MIN_RESO=25 #/100
OSC_ENVELOPE_MAX_TIME=200 #/100
OSC_ENVELOPE_MIN_TIME=1 #/100
